Description: This template deploys a KMS for secret manager
Resources:
  myKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An example symmetric encryption KMS key
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::296316970460:root'
            Action: 'kms:*'
            Resource: '*'
      Tags: 
      - Key: env
        Value: dev
  myAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: KMSSecretManager
      TargetKeyId: !Ref myKey

  # KMS:
  #   Type: AWS::KMS::Key
  #   Properties: 
  #     Description: KMS for Secret Manager
  #     Enabled: true
  #     EnableKeyRotation: true
  #     KeyPolicy: > 
  #       {
  #         "Sid": "Enable IAM policies",
  #         "Effect": "Allow",
  #         "Principal": {
  #           "AWS": "arn:aws:iam::296316970460:root"
  #         },
  #         "Action": "kms:*",
  #         "Resource": "*"
  #       }
  #     # KeySpec: SYMMETRIC_DEFAULT 
  #     KeyUsage: ENCRYPT_DECRYPT
  #     # MultiRegion: false
  #     PendingWindowInDays: 30
  #     Tags: 
  #       - Dev secret manager
