Description: Import user ssh public key to access EC2 instance. Key name is the same as email address and the fullname is in in tag

Parameters:
  ParamKeyName:
    Description: SSH keyname. Using the email (withouth domain)
    Type: String
  ParamPublicKeyMaterial:
    Description: Personal SSH public key
    Type: String
  FullName:
    Description: Fullname according to BambooHR
    Type: String

Resources:
  ik:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Ref ParamKeyName
      KeyType: rsa
      PublicKeyMaterial: !Ref ParamPublicKeyMaterial
      Tags:
        -
          Key: FullName
          Value: !Ref FullName
