# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test_aws:
    runs-on: imank-personal-mac
    steps:
      - name: test AWS version
        run: |
          aws configure list
  create_aws_cloudformation:
    runs-on: imank-personal-mac
    steps:
      - name: create_vpc_simple
        run: >
          aws cloudformation create-stack 
          --stack-name vpc-dev-exchange
          --template-body file:///$(pwd)/vpc_single_zone.yaml 
          --parameters ParameterKey=EnvironmentName,ParameterValue=dev 
          ParameterKey=VpcCIDR,ParameterValue="10.0.0.0/22" 
          ParameterKey=PublicSubnet1CIDR,ParameterValue="10.0.2.0/24" 
          ParameterKey=PrivateSubnet1CIDR,ParameterValue="10.0.0.0/23"
  create_aws_kms:
    runs-on: imank-personal-mac
    steps:
      - name: create_kms
        run: >
          aws cloudformation create-stack 
          --stack-name vpc-dev-kms
          --template-body file:///$(pwd)/kms.yaml 

